version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # check our pom.xml
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"

  # check our docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
