FROM jeroenwillemsen/wrongsecrets:1.12.1-no-vault
ARG argBasedVersion="1.12.1-no-vault"
ARG CANARY_URLS="http://canarytokens.com/terms/about/s7cfbdakys13246ewd8ivuvku/post.jsp,http://canarytokens.com/terms/about/y0all60b627gzp19ahqh7rl6j/post.jsp"
ARG CTF_ENABLED=false
ARG HINTS_ENABLED=true
ARG CHALLENGE_ACHT_CTF_HOST_VALUE="not_set"
ARG CHALLENGE_THIRTY_HOST_VALUE="not_set"
ARG CHALLENGE_RANDO_KEY_CTF_TO_PROVIDE_TO_HOST="not_set"
#ONLY OVERRIDE THE ARGS BELOW WHEN YOU ARE SETTING UP A CTF!
ARG CTF_KEY=TRwzkRJnHOTckssAeyJbysWgP!Qc2T
ARG CHALLENGE_5_VALUE=if_you_see_this_please_use_k8s
ARG CHALLENGE_6_VALUE=if_you_see_this_please_use_k8s
ARG CHALLENGE_7_VALUE=if_you_see_this_please_use_K8S_and_Vault
ARG CHALLENGE_9_VALUE=if_you_see_this_please_use_AWS_Setup
ARG CHALLENGE_10_VALUE=if_you_see_this_please_use
ARG CHALLENGE_11_VALUE=if_you_see_this_please_use
ENV APP_VERSION=$argBasedVersion
ENV K8S_ENV=Heroku(Docker)
ENV canarytokenURLs=$CANARY_URLS
ENV ctf_enabled=$CTF_ENABLED
ENV ctf_key=$CTF_KEY
ENV hints_enabled=$HINTS_ENABLED
ENV challengedockermtpath="/var/helpers"
ENV keepasspath="/var/helpers/alibabacreds.kdbx"
ENV SPECIAL_K8S_SECRET=$CHALLENGE_5_VALUE
ENV SPECIAL_SPECIAL_K8S_SECRET=$CHALLENGE_6_VALUE
ENV vaultpassword=$CHALLENGE_7_VALUE
ENV challenge_acht_ctf_host_value=$CHALLENGE_ACHT_CTF_HOST_VALUE
ENV challenge_thirty_ctf_to_provide_to_host_value=$CHALLENGE_THIRTY_HOST_VALUE
ENV challenge_rando_key_ctf_to_provide_to_host_value=$CHALLENGE_RANDO_KEY_CTF_TO_PROVIDE_TO_HOST
ENV default_aws_value_challenge_9=$CHALLENGE_9_VALUE
ENV default_aws_value_challenge_10=$CHALLENGE_10_VALUE
ENV default_aws_value_challenge_11=$CHALLENGE_11_VALUE
ENV BASTIONHOSTPATH="/home/wrongsecrets/.ssh"
COPY .github/scripts/ /var/helpers
COPY src/test/resources/alibabacreds.kdbx /var/helpers
COPY src/test/resources/RSAprivatekey.pem /var/helpers
COPY .ssh/ /home/wrongsecrets/.ssh/
CMD java -Xms128m -Xmx128m -Xss512k -jar -Dserver.port=$PORT -XX:MaxRAMPercentage=75 -XX:MinRAMPercentage=25 -Dspring.profiles.active=without-vault -Dspringdoc.swagger-ui.enabled=${SPRINGDOC_UI} -Dspringdoc.api-docs.enabled=${SPRINGDOC_DOC} application.jar
ENV slack_bot="xoxb-9228459186116-9224178209446-cnRAK5ms7Sz1Vmjbrybb4p0K"
ENV git_token="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"
ENV mongo_user="hopper"
ENV mongo_pass="Appsec@123"
ENV kibana_user="elastic"
ENV kibana_password="SuperSecretPassword"
ENV jenkins_user="jenkins_user"
ENV jenkins_key="1234567890abcdef1234567890abcdef"
ENV firebase_key="AIzaSyD-EXAMPLEKEY"
ENV aws_key="AKIAIOSFODNN7EXAMPLE"
ENV aws_secret="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
ENV stripe_key="sk_test_4eC39HqLyjWDarjtT1zdp7dc"