apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-challenge-52
  namespace: default
spec:
  progressDeadlineSeconds: 20
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: secret-challenge-52
  template:
    metadata:
      labels:
        app: secret-challenge-52
      name: secret-challenge-52
    spec:
      securityContext:
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
      containers:
      - image: jeroenwillemsen/wrongsecrets-challenge52:4
        name: secret-challenge-52
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: '32Mi'
            cpu: '50m'
            ephemeral-storage: '100Mi'
        securityContext:
          capabilities:
            drop:
              - ALL
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          privileged: true
          seccompProfile:
            type: RuntimeDefault
      volumes:
        - name: 'ephemeral'
          emptyDir: { }
