---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: default
spec:
  encryptedData:
    db-password: AgDD17JyyQWovhALxNc78jZXPEjyr13bi4nGNjZ0t6jtK6MsX6eiQQN9g4OoGp9Kwewyxg0V2VrMXUWWZG7dqEon0sPChPG2Ng6sb93gf/Qq3QaCZWW0LMKHORGOIUB6PCP1wButqdTySj3HhuNiDB0KI9hs76NJYVWAtkE2gnjxgp1h1OXwLBmPbbkrPflXLqZXYsWaCI2I6MxTilouSXV9TVxhInIgzbhtoLk0E75KkWFWNQten3oD4Ik0M3Gu4PPbyZEHFuMDyOLceWf/F7H6lCtOe6Nmu/298X0OUI5AGqbi5QKy/lZA1FSfRJPX7Ou3Wh3tfNt8U8rx+zkzc55a8huNIRWGjOqxGUaf39B8fDyV0PxXC2d/Fh/XdsvnooIFOMPg2fFhmxk9pekx/STJBs1pApfO9yBKywR8Fmc15i1BLs1jre/xuAyeWJqRZIKGahqJjldBkt1A4fulMI/jsDV0PrP5yUi8iwZ02bz/gGwb0ZlNgefd8lhXNjyd+tncIaU+fl+uBLxRtQRE7JEycUWqCsj3ED/k3mocknwrSCfeJuUUugc5nDOOa2F095GNlAnUnFgalmXKtqAJ0EYhrWVV6E6vam8kecycqZcc7jfwFuz8RqM5kw6EG5X8hNib+bzVgoeIZ8x7SvXTEaV+nxrCK1HmD1ai/YRXHwuXEIymOeb67ASOkjx4MOQVDfm+Th5vIsKiDDJejtctfBXlsA==
    db-username: AgCM6gb70nOC6QqhV75zYEgNESTSCmfSQV+CsQ5NkELVChAtHNyc2K6W/0qW9wxaQU498yjrH4oi5zI4+EwJ/AgUWUM0ftNaMXNRGSolVssYnfIwVMNHLjgWadwz4/sWGOuGZv9n79KSpxc6ry0R0osQTl9OtP6aTn2qO2Vzna/REvhZ5XUJs8+s5BxdPdcAmNWTizIIVb49cmN6a+AzHZ58x6/L/UGTD+enx75mC0S3kIp41oeiqoA4yXEkdPbCsS0r/avwswQ9thtAmx8iZWEsFyf917H5VVllgvooMI5xpOcDj3xpd8slRBgmQQMe2ghIx/ysY+rjcf18MWp0xAzSzlIR3S8Luq8dlTyX+OgIxHSP6N694+HL932pSWA0qurJ/5x2N/L5EQneSf35dAaXYcDM74BPBhFjQGcghh4r1zFdA8td9v6X0526n352S1g7qyqp4OUbTHtoaF/IpUeBE9oDz4+duzwI1ngRxmtRYb8xp081Nlw66/MWnsDaJqtHMjs97X91EPk5k0fiMwylcFYBC62glSGT30pxwbsnef2/uk5cQ4QncmlY51R3loWoUbDoN+F598PzUWbp0xVDNEwuEw8XiWJ6aUeWMuC5gv+F8FX/vyx3qyVjCabfiB0nkQCuLcuuiwR+/FOurVzpOXoYajg1+5RBHfl7USRUfpgE0pYP2QYETeT1IhpckYLlRdvFfT0cW+Y=
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: default
