---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: default
spec:
  encryptedData:
    db-password: AgABMWnvAziMQKy9ZqunxO3An+tPtIHrb5AGAVqGbtWgmk2XB/vOS676lQg7afk/PvcNWL+AcYay+JhvJAeBr7QQUa6DI2B3fTM7C3mqv4SQGN389Hat1lYWzar4MdlP7r7VEL5hjEjCeJPJyDiq9EaOUStJyM+NZFJgN1JapPFeU7w6qxUq1gpkgjbQiu/wdpHiYa8Y2/exHxyPf9vUwCneNNwrVhl7UhOtwSKiorfFL3AvxRF6+Gk5ai7PN1D+BTqA4Y4rxxBsMG/yCg2le7Gd6v03sEaETIXdl1wgrrtfjL+Olxyt+Rmm5wjXmuBm4sJvLGEJ5vujwnSjfSn3R/e2VO1iPzqXQfDm4EBXdNOlpADsxZwPfJPYBG7HCwnZblxr+DGbIdY+h3u7DpZxlrzy0GXYw17KVZJP6wRAAm07YVQwoQMPTF8Gr3BUdu5BCFzfFVXzBVR6jOxeGIBvBxF4MIQgpcc3W0vUF3czqr2QQufHyeyKOFJajuqfOGIwOmoovB5Pmvjqek/d07UrKTQBOR7CEzfZDARw/d78313yeaO2dod25iZqp7RU73OtcCvlZlTJYJuBkQiBYc0Lfu5dwFUiP1LfdiXzHTWD7OAHrDbm28mJF6mkeR/NvKouJh+5tNc/O39fraMbySdhj6bbNXui8J4V6PrRnmYLC23GtnfVtaeWTjrlOkOb1Hvv/EW+/BRi9S+wK4np/Xli6wDaCg==
    db-username: AgBZ5o4RRpncj1AcEjAqzltrWb/aAIt9JWsIvhjywbxj737/biWTuuAsGjDuoJ3wR6ZE1H6nH0QH2qMzMtHj2DCK9fxP6VOu/40v7rYIOjqbnBa7WjgumgAQg54twpHriSlOW0fmBDlLEfEBgc82CEQQRis1MJVfgCYyELdTmDIHrXHa12hm6Dvxwu8fhmgGiuMSKkaaQHCnPIn0UtzcqfGFtAwG2hkr0JDeAS7zM/D8YthDqZkRnWj3oNC5xV1sBigJDml5OHfze+y2Jx//K9glHTzichRnx2hyWiT+7X+iHlAQz0hYgIHgog2Rj3vIWIuD2B9l9qED4sHpb4usk/lgJbdC4l2w/KhBHPhu1WPc3Fg4k3fN193v/uZAWy4NenW887ms7kvFjEsxBPF5Wr/6+9YOFjxMeFYEG/fsWK3srbU89awzDsuWBmX8HR7BaeT45eSpZcyqAQU7pm3zpd4zKMIXhLoLypZ3g3GMKU5Ez6zRYEJPUc8hgCbf/n2JPXD3n9qq91SC9uCtDing8qW8wv8jVpKQEAW3/KL4ldVuTFTAjrpM/sKAtc1w2Tn0uWjoraMwL/xN7fcpax3AM+J9nDcnf1BYXJgwDI/KCfQ/zel1pjdJO3KugM1jH4cTGuVim1iOup/DbGhal1YicmuHQWC6XK5tOPrNwBnKfpz/3HiUR/UnAl6B/1xoAbDTenbuWHVy0h6GQ+A=
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: default
