name: Javadoc and Swaggerdoc generator

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
permissions:
  contents: read
jobs:
  javaDocGenerator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: "19"
          distribution: "temurin"
      - name: Clean compile docs
        run: ./mvnw clean compile javadoc:javadoc
  swaggerDocGenerator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: "19"
          distribution: "temurin"
      - name: Clean install
        run: ./mvnw clean install -DskipTests -Ddependency-check.skip -Dcyclonedx.skip=true
