# This is a basic workflow to help you get started with Actions

name: Dead Link Checker

on:
  repository_dispatch:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.4.1
        args: --exclude-all-private 
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        fail: true

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue