# This is a basic workflow to help you get started with Actions

name: Java checkstyle and testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: test with java
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test with Maven
        run: mvn test

  lint:
    name: lint javacode
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run java checkstyle
        uses: nikitasavinov/checkstyle-action@0.4.0