# This is a basic workflow to help you get started with Actions

name: DAST with ZAP on minikube

# Controls when the workflow will run
on:
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  issues: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-minikube:
    name: Test with minikube and Vault
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: eLco/setup-vault@v1
      - name: Start minikube
        uses: medyagh/setup-minikube@master
        with:
          minikube-version: 1.29.0
          driver: docker
          kubernetes-version: v1.25.6
      - name: Setup helm
        uses: azure/setup-helm@v3.5
        id: install
      - name: Setup application
        run: |
          ./k8s-vault-minkube-start.sh
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: "owasp/zap2docker-stable"
          target: "https://localhost:8080"
      - name: Teardown
        run: minikube delete
