# This is a basic workflow to help you get started with Actions

name: Test minikube script

# Controls when the workflow will run
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-minikube:
    name: Test with minikube
    runs-on: macos-11
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Install Homebrew dependencies
        run: |
         brew install helm kubectl jq vault grep minikube
      - name: Run testscript
        run: |
          ./k8s-vault-minkube-start.sh