# This is a basic workflow to help you get started with Actions

name: Test minikube script

# Controls when the workflow will run
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-minikube:
    name: Test with minikube
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: innovationnorway/setup-vault@v1
        with:
          version: '~1.4'
      - name: start minikube
          id: minikube
          uses: medyagh/setup-minikube@master
      - uses: azure/setup-helm@v1
        id: install
      - name: test script
        run: |
          ./k8s-vault-minkube-start.sh

