name: Test container on podman

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-minikube:
    name: Test with podman
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run container
        run: |
          podman run jeroenwillemsen/wrongsecrets:1.5.14-no-vault
